site_name: Practy
site_url: http://127.0.0.1:8000/
repo_name: 'Github'
repo_url: https://github.com/jabrielcjones/practy
use_directory_urls: false

theme:
  name: material

markdown_extensions:
  - pymdownx.highlight
  - pymdownx.superfences
  - admonition

nav:
  - Home: index.md
  - Running Programs:
    - Running Python: languages/running_python.md
    - Running JavaScript: languages/running_javascript.md
    - Running C Sharp: languages/running_csharp.md
  - Exercises and Questions:
    - Elementary Programming:
      - Elementary Programming Exercises: topics/elementary_programming/exercises.md
      - Elementary Programming Questions: topics/elementary_programming/questions.md
    - Math, Strings, and Objects:
      - Math, Strings, and Objects Exercises: topics/math_strings_and_objects/exercises.md
      - Math, Strings, and Objects Questions: topics/math_strings_and_objects/questions.md
    - Conditionals:
      - Conditionals Exercises: topics/conditionals/exercises.md
      - Conditionals Questions: topics/conditionals/questions.md
  - Developers:
    - Templates: developers/templates.md
  - Bibliography: bibliography.md
